apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: hello-wasm
spec:
  selector:
    matchLabels:
      app: httpbin
  url: ghcr.io/bernardtolosajr/hello_rust:v3
  imagePullPolicy: Always